function [ret] = armo(n);
% ret = ARMO([n])
%
%  Displays random quotation from professor of mathematics Armo
%  Pohjavirta.
%
%  Optional parameter n will display n:th quote. When ret is 
% defined as well will return the quote as string instead of
% displaying it.

% Get randomized or n:th quotation 
lines = get_quotes();
N = length(lines);
if(nargin == 0);
  ind = randi(N, 1);
else;
  ind = max([1, min([N, n])]);
end;

% Display or return quotation
if(nargout == 0);
  disp(lines{ind});
else;
  ret = lines{ind};
end;




function [lines] = get_quotes();
% Source for quotes:
% 
%    http://www.students.tut.fi/~funktio/armo.html
%    http://www.students.tut.fi/~funktio/are2000.htm
%
% Duplicates not removed

lines = {   
    'Matematiikka on kokemuksen monipuolisuuden funktio.' 
    'Ristitulo on kätevän ihmisen lusikka-haarukkayhdistelmä, sillä tekee mitä vain.' 
    '...pian katsotaan että sulla on vähän liian likaset alusvaatteet, niinku paremmissa piireissä.' 
    'Tällä itketettiin lapsia joskus vuosisadan alussa; suurta geometrista kamaa, heh heh! Valkoinen mies laskee vektoreilla!' 
    'Matematiikassa ei ole mitään rumaa, kaikki on kaunista.' 
    'Tässä kirjassa asiat on esitetty niin, ettei oppilaat heti ala ammuskeleen toisiaan luokassa tai nuuhkiin liimaa.' 
    'Nämä vektorit ovat aivan eri vektoriavaruuksista kotoisin olevia olentoja, on hyvin riskaabelia mennä sekoittamaan niitä keskenään.' 
    'Matemaatikon täytyy päästä sen liman yläpuolelle.' 
    'Reaalilukujen konstruointi, se on nättiä kamaa.' 
    'Kerran olen pudonnut sängystä painajaisen takia, kun olin illalla lukenut reaalilukujen konstruointia ja jotenkin niitä lukuja oli niin helvetisti, että ne tunki läpi uneen.' 
    '...Se on eleganttia kamaa. Ruoka on pantu kauniisti lautaselle, se on viehättävästi kirjoitettu, mutta tiukasti.' 
    'Työpaikalla menetätte uskottavuutenne, jos sanotte että ette viitsi tollasia arkipäiväisiä juttuja tehdä, säästätte kykyjänne tulevalle matematiikkamorsiamelle, neitseellisyyttänne säästätte, ettette likaa käsiänne.' 
    'Otan tämän vain ohimennen, että saatte vähän sielunvirvoitusta.' 
    'Ei täällä ruveta noita yli kolmannen asteen polynomeja, joissa on valmiiksi nauretut kertoimet, ratkomaan.' 
    'Insinöörille matematiikka on kuin kulmakarvat. Eihän niistä mitään varsinaista hyötyä ole, mutta otapa pois, niin johan on kumman näköinen.' 
    'Mutta perkele, huomataan, että lause on identtisesti tosi, voidaan derivoida yhtälö puolittain ja se kääntyy itseään pienemmässä tilassa.' 
    'Siinä käy aina näin kauniisti, aina saadaan ratkaistua se t jota haetaan.' 
    'Suomen kouluissa on hirveesti sälää.' 
    'Hyvä matemaatikko heti, jos on synnin tuoksuakaan ilmassa, tarkistaa.' 
    'Reaalianalyysi on suositeltava kama, valoisa, näättekö.' 
    'Ei tää (ristitulo) nyt ihan yhtä eläköön -huutoa ole.' 
    'Olen itsekin kirjoittanut ''Laaja Matematiikka 1'' -luentomonisteen. Se oli eleganttia kamaa, mutta sitä ei huomannut kukaan muu kuin minä.'
    'Mä otan tän näin, että tää näyttäis helpolta. Ettette lähde nuuskimaan sitä kuuluisaa liimaa.' 
    'Siinä on teille oikeen hyvä juttu, pysyy kätöset poissa synninteosta kun lukasette ton.' 
    'Tää kirja ikäänkuin sykkii elämää... Näättekste, tää on tosi sykkivää kamaa.' 
    'Tämä ratkaistaan ikäänkuin tulisi ääni ylhäältä, että ''Poikani, poikani, kokeilepa tuota lausetta.''' 
    'Nollafunktio on aivokuollut!' 
    'Ostakaa sellainen matematiikan kirja, jonka jorinat on kirjoitettu myötäkarvaan teistä katsoen.' 
    'Kolmioepäyhtälö pitää maailman supussa.' 
    'Hyvä sika kestää mitä vain!' 
    'Lineaarivektoriavaruus on vähän niinkuin kansandemokratia, se ikäänkuin toistaa sitä perusideaa.' 
    'Perusaksioomat pätee, vaikka oltaisiin jossain aivan perkeleellisessä reunaelementtiavaruudessa.' 
    'Tässä kirjassa on tätä fysiikkaan pohjautuvaa kamaa, sitä on kuin limaa eritetty, sitä on paljon.' 
    'Tarkoitus on, että ensin tehtävä tehdään iloisesti kuin peipponen, täysin holtittomasti apinan lailla. Sitten näättekö toisessa vaiheessa katsotaan sitä omaa sotkua epäilevästi ja kavalasti, yritetään kaikin tavoin kumota ja kampittaa sitä, herätään keskellä yötä katsomaan että ''Ei jumalauta, olisko se sittenkin ollut noin?''' 
    'Mä otan nyt viisaana miehenä axb:n sijasta bxc:n. Tuntuu kusipäiseltä, mutta katsokaa...' 
    'Oikean ja vasemman välinen ero on syvällinen, ne on ihan eri eläimet.' 
    'Ei nää määritelmät oo mitään runonpätkiä, vaan dynaamisia moottoreita, manipulatiivisia yksiköitä.' 
    'Tämä pitää paikkansa myös tavallisille, halvoille, halpamakkarafunktioille.' 
    '...Se on omikron-funktio, jumalauta! Se on sulla eksplisiittisenä siinä kätösessä!' 
    'Se kirja on sellainen, että järeinkin kaatuu puolikuolleena maahan kun katsoo sitä, koska se alkaa niin kaameella tavalla heti reunasta.' 
    'Tää lineaarikuvaus on satumaisen miellyttävä.' 
    'Kun me käytetään samaa kirjaa kuin kaikki pakanalapsetkin lämpimissä maissa, niin ei kenelläkään pitäis olla vingunnan sijaa.' 
    '...Ruvetaan silmät kiiluen määrittämään funktiota jossain perkeleellisessä tapauksessa.' 
    'Todellinen funktio voi mennä ihan kesysti, mutta tää svengaa kuin hirvi.' 
    'Yhdessä venäläläisessä matematiikan oppikirjassa oli yli tuhat harjoitustehtävää ja opiskelijoiden piti laskea ne kaikki. Ja jumalauta ne tehtävät oli sellaisia että nitroo täytyi ottaa ja varovasti kaukaa katsoa.' 
    'Kolmirivisen determinantin tapauksessa tulokset voi todistaa läpilaskemalla, millä työmäärällä lienee sovitettavissa jokin keskimääräistä niljakkaampi synti.' 
    'Toi istuu todella imevästi toi tangentti ton funktion kupeessa.' 
    'Toi menee valkosen miehen lailla helposti.' 
    'Näitä voit laskea vaikka sormilla, kunhan pidät kädet taskussa niin, ettei muut näe.' 
    'No näähän lähtee kuin mummon hammas.' 
    'Sehän on sellainen täysin kesy ja kädestäsyövä integraali.' 
    'Ylikurssia, ylikurssia. Tämä taas sarjassa ihmeellisyyksiä halvalla.' 
    'Me käsitämme vaaka- ja pystysuoran jotenkin niin, että vesi on vaakasuorassa ja ihminen sitten hoippuu pystysuorassa siinä vetten päällä.' 
    'Se on niinku sama että kivi ei pysy veden pinnalla - saa sitä yrittää.' 
    'Ei jumalauta sellaista Tarzania ookkaan, joka näitä funktioita rupeaisi vääntään jollain epsilon-delta -tekniikalla!' 
    'Kaikki tavallinen töhkä on jatkuvaa.' 
    'Tässä lähestymistavassa on pelkkää valoa ja rakkautta, kaikki on kaunista, mikään ei tee kipeää.' 
    'Kirjoja lukiessa usein ihmettelee, että ''Miksi jumalauta valitaan noin?'', mutta lopussa kun pöly laskeutuu niin nähdään, että kaikki epsilonit laskeutuu yhteen ja niiden summa on tasan epsilon.' 
    'Huomaatte, että tää on kätevän ihmisen kamaa, että ''Ei jumalauta, näinhän sitä polkupyörääkin korjataan!''' 
    'Kun sä determinantista poistat tän yhden rivin, niin kyllä siinä jumalauta ne samat rivit kukkii samassa järjestyksessä.' 
    'Ei me tehdä numeerisessa laskussa eroa vektorien ja matriisien välille. Eletään niin kuin pellossa. Ei satu lainkaan ja on mukavaa.' 
    'Maxwellin yhtälöt on sellaisia, että ne hyydyttää raavaankin aikuisen.' 
    'Kun ihmiset on 30 vuotta opettanut samalla tavalla ja sitten tulee joku nuori mulkku matematiikan laitokselta, niin siellä on kaikilla pärstä auki. Ei se vetele.' 
    'Tää ohjelma (Matlab) on aivan ihana, sillä ei mee koskaan luu kurkkuun. Sä voit syöttää sinne ihan mitä vain ja jumalauta aina soi!' 
    'Lokaalinen linearisointi on laskennallisesti miellyttävä, se on laskennallisesti yhtä juhlaa.' 
    'Kun liikutaan x-y -suunnassa niin kaikki on tasaista ja kaunista, kaikki on nättiä ja jatkuvaa, mutta jos lähtee johonkin välisuuntaan niin heti on otsa kurassa.' 
    'Jos mun pää on pinta ja siihen pannaan tangenttitaso, niin korvataan linearisoimalla mun pääni.' 
    'Jos maailma on tasaisesti ja rauhallisesti jatkuvaa niin ei siinä mitenkään derivaatat äärettömiin pamahda, vaan kyllä siinä joku patologinen tilanne on, että terve osaa olla heti varuillaan.' 
    'Implisiittisesti ymmärretään, että Akilles on aika pinkoja.' 
    'Yks tehtävä, jonka piti mennä, ei mennyt ja yks, jonka ei pitänyt, meni... Luonto tasoittaa.' 
    'Derivaatta täytyy määritellä niin, ettei sun tarvi mennä tökkiin niitä muuttujia yksitellen teroitetulla coctailtikulla.' 
    'Käytä tarvittaessa Matlabia liberaalisti kuten rasvaa.' 
    'Vektorianalyysi on ihan eläinoppia.' 
    'Se on jo toinen ratkaisu ja se konvergoi niin, että kuuluu huminaa.' 
    'Suurin osa matematiikasta menee mekaanisesti, köps köps köps, niinku hevosella, näättekö.' 
    'Vektori on mutkikas olio.' 
    'Tässähän on jotain petomaisen tuttua, eiks oo?' 
    'Onhan se sievä merkintä, mutta kun ei yhtään tiedä juodaanko sen kanssa punaviiniä vai valkoviiniä.' 
    'Tän kun te kestätte, niin saatte kärsimyksen syvät uurteet otsaanne ja se antaa oikein jalon leiman teille.' 
    'Ei siinä oo mitään ihmeellistä, se tehdään vaan suoraan reunasta, ihan kylmästi reunasta, sit se vastaavasti luetaan reunasta... Ei pidä säikähtää, siitä vaan reunasta.' 
    'Viepä kotiin vanhalle tädille nähtäväksi lineaarikuvaus.' 
    'Kun vetää asiat 12 prosenttia nopeammin, niin ääni ei nouse kuin yhden sävelaskeleen, ja sitä ei käytännössä edes huomaa.' 
    'Hei, pannaas tonne k ettei oo kusetusta, lasketaan päärynällä eikä omenalla.' 
    'Jos sä otat jokaisen Martti Ahtisaaren niin on helvetin suuri todennäköisyys, että jokainen vastaantuleva eläin on ihminen.' 
    'Säähän voit kuvitella, että tää on saatanallisen näköinen funktio. Tässähän voi olla mitä tahansa hirmuisia funktioita.' 
    'Tossa kirjassa on semmoista elämän sykettä, mutta se on kaikki falskia moskaa. Ei semmosta helppoa nakkia olekaan, että te voisitte tulla sankarina paikalle ja ratkoa toisten ihmisten ongelmat.' 
    'Te saatte täällä vähän liian optimistisen kuvan, että siitä vaan reunasta, mutta ei se jumalauta mene.' 
    'Tää kirja on vähän harhaanjohtava kun siinä matriiseja sorkitaan käsillä. Ei semmoista tehdä!' 
    '...Mun mielestä se on vähän väärin niitä kohtaan jotka on tehny hommia niin, että veri on perseestä lentänyt.' 
    'Jos te rupeette jakaan vektoreilla, niin meidän elämä on valunut hiekkaan.' 
    'Tässä vuoden kuluessa itse kukin alkaa kehittään pihkatappia takapuoleen, että tekis jo mieli vetäytyä johonkin juurakon alle.' 
    'Me jätetään se Gaussin eliminaatio pois, se on tommosta saakelin sorkkimista.' 
    'Ja ennen kuin sormi on returnilla rupee lukuja lentään kaaressa takapuolesta.' 
    'Ne on numeerisia integraaleja, joita kone laskee mielipuolen himokkuudella.' 
    'Tää koko homma perustuu siihen, että terve näkee heti, että kätevä ihminen osaa muodostaa tän...' 
    'Tässä ei oo mitään rahvaanomaista vääntämistä, hiki ei nouse pintaan missään vaiheessa.' 
    'Terve yrittää välttää likaista työtä ja nähdä asian suoraan, ihan otsan kirkkaudella.' 
    'Mun mielestä se on niin kauniisti tiivistetty: kun mulkkuna syntyy niin mulkkuna kuolee.' 
    'Tätä toista riviä ruvetaan lisäämään kavala tähtäys silmässä, että saadaan tapettua nää luvut...' 
    'Ne luvut on menettäneet identiteettinsä... Ne on kaikki liuenneina siihen lukujen mereen ja ne on vaan yks saakelin reaaliluku, joka ei muista omaa historiaansa.' 
    'Kolmioepäyhtälö takaa sen, että me ei jouduta hevon kuuseen matemaattisesti, jos me otetaan n pientä askelta.' 
    'Joku rontti paskiainen tulee humalassa tenttiin ja vetää täydet... On se niin väärin.' 
    'Jos te ootte viettäneet huikentelevaista elämää koko tenttiviikon tai ootte jotenkin muuten ollu kateissa, niin ettei se kaikki oo kiinni siitä yhdestä tentistä...' 
    'Ei pääse livahtamaan äärettömyyteen mitään...' 
    'Terve näkee heti, että tossa ykkösessä voi tapahtua jotain ihan hirveää.' 
    'Ei meillä ole mitään syytä nuuskia tota o:ta.' 
    'Ei oo mitään järkee ottaa itselleen lisähuolia erottamalla tota lineaarista osaa ja sitten naida tota o:ta jotenkin innostuneesti.' 
    'Tää on tän matikan vaikein osa, se tappaa teiltä täit turkista välittömästi... Kyllä se siitä sitten kesyyntyy...' 
    'Tää determinantti on tavattoman komplisoitu elukka.' 
    'Eikö mee nätisti? Ei kyyneleitä lainkaan.' 
    'Näissä on mielenkiintoinen struktuuri. Kannattaa katsoa suurena valkoisena vanana näitä lauseita.' 
    'Tää on kuin mielipuolen askarteluoppaasta tehtävä 7.' 
    'Olisi kohtuutonta odottaa, että nuoret älykkäät ihmiset olisivat kiinnostuneita jostain helvetin aksioomista.' 
    'Mäkin oletan, että jos mä oikeen pahasti sanon teille, niin teistä alkaa kasvaan matemaattista rönsyä ja erilaista nuppua ja lehteä rupee tunkemaan esiin.' 
    'Hei, tää on ihan nätti. Ei mitään rumaa ja hiki ei lennä, näättekö?' 
    'Jos sä lasket tän käsillä niin siinä menee nuoruus ja vielä vanhuuskin, ei se käy.' 
    'Näin tekee sivistynyt ihminen, joka ei toimi elukkain lailla.' 
    'Mistä helvetistä te tiedätte, jos joku tuntematon mies asematunnelissa antaa teille 7 vektoria, että ne on lineaarisesti riippumattomia?' 
    '...Aivan päinvastainen tulos voidaan todistaa ihan yhtä letkeesti.' 
    'Aina sanotaan, että tostakin näkee suoraan ja näkee suoraan, mutta EI JUMALAUTA NÄÄ!!!' 
    'Nää lausekkeet rupee hyvin pian näyttään sellaisilta, että täytyy ottaa nitroo.' 
    'Mää joudun tässä typografisesti tiettyyn syöksykierteeseen.' 
    'Otat jumalauta pussillisen vektoreita niin, että ne virittää koko V:n!' 
    'Kortti tuo ja kortti vie, mutta matikan arvosana on onnen kauppaa.' 
    'Tällainen valaistus tekee hyvää teidän aivolisäkkeelle. Muuten teille kehittyy pihkatappi takapuoleen ja jonain aamuna kun heräätte niin huomaattekin, että on huhtikuu, näättekö.' 
    'Mä tykkään ajatella näitä näiden epsilon-pallojen avulla. Hullut tykkää pyörinnästä ja pyöreästä, se tiedetään.' 
    'Hei, en mä kysy tätä tentissä. Leikkiä tää vaan on, talo tarjoaa.' 
    'Kannattaa valkoisen miehen lailla ajatella, ettei tuu liikaa työtä.' 
    'Miten tää homma voitais hoitaa syksyllä niin, että neliöihmiset menis kulmikkaaseen reikään ja pyöreät ihmiset pyöreään reikään?' 
    'Täältä eturivistä eräs ystäväni ja kollegani, valkoinen mies ja upseeri, antoi tällaisen ehdotuksen...' 
    'Kun sä sijoitat tän aivan poliisin lailla mitään ajattelematta...' 
    'Tietokoneella pystyy generoimaan elämää suurempaa dataa käsin koskematta ja itteensä likaamatta.' 
    'Otetaan tää leikkinä. Mää myyn matikkaa.' 
    'Ostaisitko käytetyn insinöörimatikan opiskelijan? No en ostaisi! Nykyään ei oo käteviä ihmisiä, puuttuu semmonen päällekäyvä kätevyys. Asiaa pitää jumalauta pudistella kunnes se selviää. Tää koko homma pyrkii semmoseen kätevyyteen.' 
    'No terve rupee heti kattoon, että ei perkele, että olisko tää miniminormitehtävä... Ja piru, se on!' 
    'Se oli armeijassa niin mukavaa teltan lämpimässä kynällä piirtää valkoisena miehenä niin ihmeellisen ihania hajontoja.' 
    'Sä oot ihan oikeessa. Aivan kusipäinen yrityshän toi oli.' 
    'Tää todistus on ihan helppo, sehän lähtee tosta jumalauta ihan suoraan, irtoo niinkuin mummon hammas.' 
    'Ei pidä tuntee itteensä tyhmäksi jos näitä ei heti ymmärrä. Näitä pitää tutkia täydellisen mielenrauhan vallitessa.' 
    'Ei tästä (matematiikasta) kannata ottaa mitään paineita. Tärkeintä on se, että muistaa ottaa rauhallisesti. Ihan leikkiähän tää vaan on.'  
    'Tän aksiomaattisen käsittelyn tarkoitus on, että te huomaisitte olevanne laajassa matematiikassa, eikä insinöörimatematiikassa, että se herättäis vähän ajatuksia, että ‘Kattokaa nyt jumalauta!’. Otetaan luulot pois heti kättelyssä, että paska putoo pois rattailta.'
    'Tää Eulerin kaava on kätevä taskussa, näättekö. Herrasmies ei hikoile tällaisissa.' 
    'Eihän toi Euler mikään vähäinen äijä ollut, tietenkään.' 
    'Mä otan nyt aivan nautamaisen yksinkertaisen esimerkin.' 
    'Matematiikan laitoksella me ollaan siveyspoliiseja, me sensuroidaan matemaattisia julkaisuja vähän, jos on hameenhelma liian ylhäällä tai jotain sellaista, ettei oo mitään liian rietasta.' 
    'Hyvä että huomautatte näistä mun virheistä, tässä lähitaistelussa tulee aina vähän tällaisia...' 
    'Ajatellaan, että meillä on käytettävissä pelkästään sellainen ehto, että ’Jos eläin on Tarja Halonen, niin eläin on ihminen’. No jos sitten jossain pimeessä metsässä mönkii vastaan joku karvainen otus, niin meidän on pirun paha mennä tollasen ehdon perusteella sanoon, että pureeko se vai lyökö se, koska se on niin julma se ehto. Olis paljon helpompaa jos olis jotain lisäehtoja, kuten ’onko sillä Kela-kortti mukana’ tai ’haiseeko se viinalle’, tai jotain tällaista.' 
    'Tää nykyinen suorakulman merkintätapa on huomattava parannus koulumatematiikassa. Se on jotenkin paljon jämäkämpi ja lapset pysyy ryhdikkäinä.' 
    'Täällä oli kerran yks tyyppi, joka suoritti kaikki matikankurssit parhailla arvosanoilla. Se istui aina tossa eturivin keskellä, joka kerta samassa paikassa, ja joka ikisellä luennolla se nukkui autuaallisesti, pää takakenossa, sen näköisenä, että siunaava sade lankesi sen päälle. Ja sitten,  näättekö, kun luennolla tuli joku jännittävä kohta, jossa tuli jotain tärkeää, niin silloin se heti heräsi, silmät kirkastui ja se alkoi tehdä muistiinpanoja. Kun se jännittävä kohta meni ohi, niin sitten se taas nukahti. Opintojensa loppuvaiheessa se osas jo nukkuakin kynä kädessä, koko ajan valmiina kirjoittaan.' 
    'Me määritellään determinantti niinkuin virastossa, sillai ikävästi. Se vain paiskataan teidän eteen ja sanotaan että ’opi tuo tai kuole’... tai jotenkin näin.' 
    'Matriisi tulee muistaakseni jostain latinankielestä ja tarkoittaa kohtua. Matriisissa on lukuja tietyssä järjestyksessä, siis sillai niinku äidin masussa kauniisti uinuvat.' 
    'Eihän sikakaan rupee tällaista laskeen käsin, vaikka eihän se oo kuin puolen tunnin juttu... Mutta herrasmies on herrasmies.' 
    'Persetti, tulikin tosta mieleen, kun mulla oli kerran luento maanantaiaamuna ja tossa eturivissä istui kaksi kaunista tyttöä, jotka kovaan ääneen kertoi toisilleen, mitä viikonloppuna oli tapahtunu. Mulla tuli taulukin täyteen virheitä, kun keskityin vaan kuunteleen niitä. Ja jumalauta ne puhuikin vaan jotain, että kuinka ne oli ostanu maksalaatikkoo tarjouksesta ja sitten lämmittänyt sitä mikrossa ja säästänyt puolet siitä seuraavalle päivälle... siis kauheen pitkäveteistä juttua. Ja mää kun odotin jo kuulevani vaikka mitä!' 
    'Jos sä otat jonkun pisteen, vaikka kuinka pirun läheltä ykköstä, niin aina sinne väliin mahtuu pisteitä, jotka käyttää rexonaa... vai miten se nyt meni.' 
    'Ei näissä vektoriarvoisissa funktioissa mitään niin ihmeellistä ole, että pitäis kuvitella että ne olis jotain pimeessä loistavaa.' 
    'Minimointialgoritmin täytyy jotenkin kopeloida sitä ympäristöönsä, että se tietää mihin suuntaan pitää mennä. No mistä se sit tietää, että missäpäin on alamäki? No esimerkiks kusasee ympäriinsä ja lähtee sinnepäin mihin se lirisee.' 
    'x-y –taso ei ole rajoitettu alue, koska se menee hevon kuuseen.' 
    'Toi on tollanen kompakti merkintä, että sun ei tartte turpaas turhaan lörisyttää, kun merkkaat noin. Onhan se vähän kökkö, kun se jättää lukijan auki, että ’Mikä piru toi on?’' 
    'No tässähän tulee ensimmäisenä mieleen, että mistä jumalauta tollanen delta saadaan? Tää menee niin, että enkeli taivaasta tulee ja antaa sulle silkkipaperiin käärittynä ton deltan.' 
    'Jotain tällaistahan usein insinöörimatikan puolella tarjotaan: sin(x+y) = sin(x) + sin(y)... No älkää nyt helvetissä kirjoittako tätä, mä vaan näytän.' 
    'Tää pitää kirjoittaa näin; siis kattokaa nyt kun setä tekee töitä.' 
    'Vaikka sulla olis kuinka räkäinen funktio, niin sä voit approksimoida sitä lineaarisesti.' 
    'Lebesgue-integraali on vähän niinkuin ne Brezhnevin aikaiset puheet kansojen ystävyydestä; aina puheissa läsnä ja kauheen tärkeitä, mutta käytännössä niitä ei näy missään.' 
    'Kreikkalainen kirjain ’ksi’ on vähän sellainen, kuin mitä kalkkunalla roikkuu nenässä, näättekö, sellainen loputon hytinä ja tutina.' 
    'Kun joku tehtävä näyttää siltä, että kun pikkuisen vetää henkee, niin se menee, mutta sit ei jumalauta menekään, niin se on tosi ikävää... Siis just se kun näissä hommissa joskus aina tulee täysin varoittamatta turpaan, se on ikävää. Mä otan osaa, otan kovasti osaa.' 
    'Muistakaa sitten kokeessa oikein kovasti luntata naapurin paperista. Se on nimittäin hyvin todennäköistä, että juuri se teidän vieressä istuva kaveri on uudestisyntynyt Gauss.'
    'Toi tulos ei sovi käsinlaskentaan, paitsi jossain rangaistuslaitoksissa.' 
    'Ensimmäisten lentokoneiden siipiä mallinnettiin 2-ulotteisina. No sittenhän näitä alkuaikojen sankareita kopsahteli maahan aika tiheeseen tahtiin.' 
    'Mä merkkaan tätä integroitavaa nyt pelkällä f:llä, jos lupaatte olla turmeltumatta. Älkää turmeltuko.' 
    'Kun joku insinöörimatikan puolelta alkaa kirjoittaan jotain matemaattisia papereita, niin niillä alkaa puntti tutista, kun pelottaa kirjoittaa jotain sellaista, mitä ei itse ymmärrä. Siinä ne sit ihmettelee jotain Lebesgue-integraalia, että ’Mikä helvetti tommonen L on?’' 
    'Jos sä valitset noi integrointirajat niin, että sä paukkaat sinne jotain sopimatonta, niin integraali voi aika äkkiä mennä perseelleen.' 
    'Näitä laskettiin käsin silloin, kun ei vielä ollut noita numeriikan ruhjomalaitteita ( = tietokoneita).' 
    'Opiskelijoita varmaan kiinnostaa monet muut asiat enemmän kuin matematiikka, mutta meille tää on jumalauta maailman tärkein asia ja se seisoo jääkaapin kokoisena tossa edessä ja pimentää kaiken muun.' 
    'Helvetin hyvä, että huomautit tosta mun virheestä, mä oon vielä vähän uninen. Mä meen tässä ihan niinku hevonen, klipiti klopiti.' 
    'Vektorit on käteviä geometriassa; käyttäkää niitä, huvitelkaa niillä, jossain kesäisissä olosuhteissa, jossain maalla. Ei tartte olla ihan selvänäkään. Jos laskette jotain niin laskekaa vektoreilla.' 
    'Yhdessä opintomonisteessa oli sellainen harjoitustehtävä, että ’todista Hahn-Banachin lause.’ No sehän on ihan helvetin hyvä harjoitustehtävä jos sä satut olemaan Hahn tai Banach, tai jos oot työskennellyt alalla 30 vuotta. Ei se kyllä jumalauta muuten onnistu.' 
    'Matematiikan todistuksien pitää olla täysin aukottomia ja niitä pitää tarkistettaessa tuijottaa oikein pahalla silmällä, näättekö, ja antaa kaverienkin katsoa pahalla silmällä, sillai oikein mulkkumaisesti, eikä pidä loukkaantua siitä, jos ne löytää jonkun virheen.' 
    'Teidän pitäis vastata tällaiseen matematiikan opiskeluun liittyvään kyselyyn. Kirjoittakaa siihen mitä ajattelette tästä, mutta noiden palautepapereiden lukija on naispuolinen, joten älkää käyttäkö sanontaa ’kurssi on perseestä’.'
    'Mulla oli kerran tuolla keskustassa autosta potkittu lyhdyt rikki. No mä menin sit heltta punaisena poliisiasemalle tekeen ilmoitusta. Sellainen iso musta poliisi istui siellä tiskin takana ja luki aamulehteä. Kun mä esitin asiani sille, kerroin että lamput on potkittu rikki, niin se nosti väsyneen katseen lehdestä ja sanoi: ''Maailmassa tapahtuu kaikenlaista.''  Siis se oli ihan helvetin hyvin sanottu!!! Heti jotenkin helttakin painui takaisin kasaan!'
    'Jos ajattelette sitä Banach-Tarskin paradoksia, missä pallo jaetaan osajoukkoihin, ja kun ne palaset kootaan uudestaan niin niistä voi tulla ihan minkälainen kappale tahansa, niin eihän ne osat tietenkään mitään pyhäkoulujoukkoja voi olla; niidenhän täytyy olla ihan sikapatologisesti määriteltyjä.'
    'Kohinaisesta datasta kerätyt mittauspisteet on ihan juosten kustuja.'
    'Tää todistus on esitetty siellä monisteessa, mutta sitä on vähän ikävä katsoa sieltä. Katsokaa varovasti, ettette pahoita mieltänne.'
    'Tohon x:ään pitää assosioida sellainen tiheysfunktio, joka haisee x:ltä.'
    'Jos kultasepänliikkeen ikkuna lyödään rikki ja sieltä viedään tavaraa, ja sitten poliisit tulee paikalle ja löytää liikkeen edestä äijän, jolla on taskut täynnä koruja, mutta joka kuitenkin väittää ettei ole rikkonut ikkunaa ja varastanut niitä, vaan että ne korut on jotenkin kvanttimekaanisesti tunneloitunut sinne taskuun, niin silloin herää kysymys, että uskoako äijää vai ei. No onhan sille tunneloitumiselle jokin äärellinen todennäköisyys, mutta se on niin pirun pieni, että riittääkö se evidenssiksi, varsinkin jos äijä on muutenkin luihun näköinen.'
    'Tässä nyt näkyy se, että miksi on olemassa sellainen parempien lasten vähän vauhdikkaampi multinormaalijakautuma.'
    'Hei, tää on ihan leikkiä vaan, ei pure. Ei irtoa taulusta ja kipitä sinne puremaan teitä.'
    'Eihän kukaan voi tietää natiivitilassa, juuri äidin kohdusta tulleena, että mikä on joku pirun aliavaruus.'
    'Tätä asiaa kannattaa vähän mietiskellä, tää on aika hankala. Mä oon kysyny tätä joskus tentissäkin, mutta sitä on aina joutunu juopottelemaan sen jälkeen suuren synkkämielisyyden vallassa.'
    'Joskus tarttui vaatteisiin yks Moskovan yliopiston tilastomatematiikan opetusmoniste, joka koostui kahdesta osasta. Se ensimmäinen osa oli ihan pelkkää mittateoriaa. Se oli kuin petolinnun perse, tosi tiukkaa ja vaikealukuista, mutta sitten se toinen osa oli sellaista, että  ''hei hei, älä nyt vaan huolestu, tässä on vaan tällaisia mittoja ja annan sulle tuhat ruplaa, jos lasket tän integraalin''.'
    'Toi matriisi XTX on ihan pieni, eihän se vaadi tietokoneelta mitään, tollasen surkeen rääpäleen kääntäminen. ... Ja sit toi XT makaa tossa perässä litteenä kuin luumu.'
    'Tässä nää vektorit on ihan rehellisiä rasvanahkaisia lukuvektoreita, ihan konkreettisia. Helisevät pussissa, näättekö.'
    'Kyllähän tentissä kannattaa vähän ajatella, että mitähän se mulkku tässä nyt kysyy.'
    'Jos dataa kuvataan pelkillä luvuilla, ilman mitään jakautumia, niin eihän siitä ota mitään selvää. Se on vähän sama kuin mä sanoisin, että ''Hei hei, mä oon Armo, mä olen 3,85. Mitäs sä oot? No mä oon 11,7.  Ahaa, joojoo...''.  No mitähän pirua se sitten tarkoittaa, näättekö?'
    'Sen pienimmän neliösumman käyttöä perustellaan jotenkin niin, että se on lapselle sulavaa ruokaa.'
    'Eikös tää pseudoinverssi X+ ole ryöppäämisen jälkeen syötävää? Vai mikä piru toi merkki oli?'
    'Mä oon kerran elämässäni pelannu pokeria. Se oli joskus opiskeluaikoina, kun mä pelasin yhden vanhan juopon arkkitehdin kanssa. No mä olin laskenu ihan hirveesti kaikkia korttipeliin liittyviä todennäköisyyksiä ja mulla oli monta paperillista kaikenlaisia taulukoita mukana kun mä menin pelaan, ja silti se tyyppi kyni mut kertakaikkiaan heti. Se homma perustui siihen, että se näki mun naamasta heti millaiset kortit mulla oli, mutta sen naamasta ei nähnyt yhtään mitään. Eihän kortinpeluu perustu mihinkään todennäköisyyksiin, vaan huijaamiseen ja pettämiseen.'
    'Insinöörit käyttää jotain Laplace-muunnosta sillä tavalla suu vähä-älyisesti puoliavoinna, sylki valuu suupielestä. Se on pelkkä apuväline.'
    'Lasten pituuskasvuahan mallinnetaan normaalijakautumalla. Sen mallin mukaan jostakin saattaisi periaatteessa löytyä 5-vuotias lapsi, joka on miinus kolme kilometriä pitkä! Vaikka olishan sellainen tietysti aika harvinaista.'
    'Eihän sun tentissä tartte mitään ajatella, jos tällainen tehtävä tulee. Pökäät vaan ton laskun sinne ja teet niinkuin käsketään. Saat jumalauta vitosen ja elät onnellisena elämäs loppuun asti.  Prinsessa ja puoli valtakuntaa.'
    'Tää on hyvä kirja, mä suosittelen tätä. Tää pitäis löytyä tuolta korkeakoulun kirjastostakin, ellei sitä sitten ole varastettu. Sieltähän on yleensä kaikki parhaat kirjat kadonneet, kun joku on tietysti ajatellut, että sääli pitää noin hyvää kirjaa täällä kun ei noi mulkut sitä kuitenkaan ymmärrä lukea.'
    'Pitäisköhän tässä nyt tehdä niin kuin aikoinaan Itävalta-Unkarin armeijassa, kun husaareille opetettiin miten vikuroivaa hevosta käsitellään. Sitä lyödään heti nyrkillä korvien väliin. Joko se kuolee siihen paikkaan tai sitten se on säyseä koko loppuelämänsä. Mä aattelin samalla tavalla, että jos nyt otettais se muuttujan vaihto, niin sen jälkeen te ette enää pelkää mitään, ootte täydellisen karaistuneita sankareita. Jos te tästä selviätte elävänä, niin se kurssin loppu onkin sitten vaan pelkkää heinänsyöntiä ja piereskelyä, niinku jossain vähän paremmassa ratsuväessä.'
    'Toi k-muoto on sellainen kuvaus, joka syö vektoreita ja paskoo toisesta päästä ulos lukuja.'
    'Ton kirjan alkuosa on luonteeltaan sellainen, että se on kirjoitettu joillekin amerikkalaisille college-tytöille; siellä on moniston orientoinnin yhteydessä piirretty jotain sormien kuvia ja kerrottu, että moniston voi tehdä paperimassasta ja värittää sen vesiväreillä... tai jotain siihen tyyliin, näättekö.'
    'Me otetaan tää ihan urheiluna, näättekö. Koittakaa ottaa tää sillai positiivisen rennosti, eikä niin että joku mulkku kyylä laittaa tän kokeeseen.'
    'Jos käytte tuolla laitoksen kirjastossa, niin vilkaiskaa samalla noitakin kirjoja. Mua nimittäin kiinnostais tietää teidänkin mielipiteet siitä, että onko se äijä tehnyt noiden kirjojen kansikuvat LSD:n vaikutuksen alaisena, kun ne on niin riemastuttavan ufoja.'
    'Toi kirja on sellainen, että siellä vaan sanotaan että joku asia on helppo todistaa, mutta sit kun sä rupeet todistaan sitä niin kohta sä huomaat että sä et oo moneen päivään ajanu partaas, jumalauta!'
    'Tää on aika vaikea kirja, tätä käytettiin seminaarikirjana joskus 90-luvun alkupuolella ja etenemisvauhti oli sama kuin Stalingradin taisteluissa, siis jotain tyyliin: Joukkomme ovat tänään sankarillisten taisteluiden jälkeen vallanneet kylpyhuoneen ja keittiön.' 
    'Tossa kirjassa tää todistus menee tosi kauniisti, ei lainkaan hikeä ja kyyneleitä, siinä ei tartte tehdä yhtään rehellistä työtä. Mutta jos yritetään tehdä sellainen suora raaka ratsuväenhyökkäys, näättekö, niin siinä on kyllä kypärät kohta kallellaan... Mutta se on kuitenkin ihan opettavaista käydä sen todistuksen päälle ihan rintamahyökkäyksellä, vaikka siinä voi kyllä äkkiä tulla äitiä ikävä. Mä yritin sitä eilen illalla, enkä saatana saanu sitä menemään.' 
    'Mä oon tätä todistusta katsonut monesta kirjasta, mutta tota yhtä kohtaa ei oo jumalauta missään perusteltu mitenkään. Se on vaan annettu vähän niinku jossain Strömbergin valimon ruokalassa, missä se soosi vaan läiskästään sun etees: plöts, tossa.'
        };

